language: python

python:
  - "2.7"

env:
  - VERSION="8.0" ODOO_REPO="vauxoo/odoo"
  - VERSION="8.0" ODOO_REPO="vauxoo/odoo" UNIT_TEST="1"

virtualenv:
  system_site_packages: true

install:
  - git clone https://github.com/oca/maintainer-quality-tools.git -b master ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  #- ${TRAVIS_BUILD_DIR}/travis/travis_install_ifrs_nightly ${VERSION}

script:
  - travis_run_tests ${VERSION}

after_success:
  coveralls
